### ISSUE TITLE
load usage help text for samples from file

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/SparkCLR#106]
Improve PrintUsage implementation in https://github.com/Microsoft/SparkCLR/blob/master/csharp/Samples/Microsoft.Spark.CSharp/Program.cs#L215. Instead of inline strings, help text could be loaded from a text file. This help file can be referenced in readme file also.

**Comment by ms-guizha** [comment]
I will take this one , any one who has assignment acess and can assign it to me

**Comment by qintao1976** [comment]
Have assigned this issue to you. thanks

**Comment by ms-guizha** [comment]
I have sent out PR

**Comment by skaarthik** [comment]
Thanks @ms-guizha for addressing this issue. Merged your PR to master.
