### ISSUE TITLE
Continuous integration for both Windows and Linux systems

### ISSUE THREAD

**Issue by kai-zeng** [Microsoft/SparkCLR#120]
In order to provide stable Linux compatibility for SparkCLR, we need to set up continuous integration for Linux. AppVeyor does not have Linux support. I have experimented with Travis CI, which worked well for SparkCLR on Linux. Travis CI uses xbuild for building, and supports NUnit for testing. It also support OS X, but it does not support Windows yet.

One option to our problem is to host our own Jenkins service, which does support both Windows and Linux. Another option may be having two CI tools at the same time.

The tasks of adding support for Linux can be divided into:
1. Having a Linux version of the Build/Test/Clean scripts, including all Build.cmd's, Clean.cmd, RunSamples.cmd and Test.cmd.
2. Setting up CI configuration

**Comment by skaarthik** [comment]
We can go with two CI services for now - AppVeyor for Windows and Travis for Linux. We can consider hosting Jenkins if we see any compelling reason for it.

**Comment by kai-zeng** [comment]
I have finished task 1: preparing scripts for linux.
There is one compatibility issue: Spark's PythonWorkerFactory has two mechanisms for managing Worker processes: (1) directly launching worker processes; (2) lauching workers through a daemon process.
Currently to make samples run, I am using a modified spark-assembly jar which only use approach (1) to manage workers.

To Linux support on board as soon as possible, I think we should use this modified spark-assembly jar for testing/running samples, and put instructions in ReadMe for users who want to deploy on Linux. But we should make our Worker compatible with the second mechanism, the same as pyspark. I will create an issue about this.

Thoughts? Also, where to host the modified spark jars?

**Comment by kai-zeng** [comment]
Fixed by PR #157
