### ISSUE TITLE
Update Pom.xml to support creating uber package as a separate goal

### ISSUE THREAD

**Issue by danielli90** [Microsoft/SparkCLR#130]
Pom.xml is ued to produce lean and mean SparkCLR package by default. This default Pom.xml supports debug mode in IDE like IntelliJ. For end-2-end testing and job submission, as a workaround, build.cmd modifies pom.xml at build-time to produce uber SparkCLR package which includes dependent packages (PR#127)

The workaround needs to be replaced by a separate goal in Pom.xml, explicitly.

**Comment by danielli90** [comment]
maven profile seems a solution here - http://stackoverflow.com/questions/4519672/maven-alternate-pom; http://maven.apache.org/guides/introduction/introduction-to-profiles.html.

**Comment by qintao1976** [comment]
I think this is solved by PR #197.
