### ISSUE TITLE
move build artifacts out of scripts folder

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/SparkCLR#131]
https://github.com/Microsoft/SparkCLR/tree/master/scripts folder was originally meant for scripts that will be included in the release (like sparkclr-sumibt). If we want to stick to that original scope, we need to move build-related scripts like addotherplugins.ps1 out of it.

**Comment by danielli90** [comment]
we can create a new "build" top-level directory and move build-related scripts there.

**Comment by skaarthik** [comment]
With the recent addition of Linux scripts, I think it will be better to add two build folders for Windows and Linux each soon.

**Comment by qintao1976** [comment]
addotherplugins.ps1 has been removed by PR #197.  But there is still script "zipdir.ps1" remaining in this folder.

**Comment by skaarthik** [comment]
Fixed with https://github.com/Microsoft/SparkCLR/pull/224
