### ISSUE TITLE
set executable name as app name

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/SparkCLR#147]
"org.apache.spark.deploy.csharp.CSharpRunner" shows as the app name in Spark UI. All SparkCLR apps will have the same name if app.name is not explicitly set. We could set exe name as the app name if it is provided explicitly.

@tawan0109 - I vaguely remember fixing this issue a while back. Did anything change recently?

**Comment by tawan0109** [comment]
@skaarthik for now I can't recall any changes that may be related to it. Let me do a quick fix to bring it back first.

**Comment by tawan0109** [comment]
@skaarthik This issue closed automatically after I merged the PR #148 , please reopen it if you think it needs more investigation.
