### ISSUE TITLE
Build.cmd failed when Nuget.config is modified by other application

### ISSUE THREAD

**Issue by rogerpengyu** [Microsoft/SparkCLR#161]
I hit the build.cmd error in building csharp folder. Digging into it I found the "nuget restore" didn't pull the packages into the correct folder, instead, it pulled the packages into a shared folder. This is because I have a pacman main empty enlistment in the same computer, which changed the nuget.config as:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <activePackageSource>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </activePackageSource>
  <config>
    <add key="repositoryPath" value="c:\src\CxCache" />
  </config>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
</configuration>

at C:\Users\rogeryu\AppData\Roaming\NuGet\NuGet.Config

This makes nuget to pull packages into c:\src\Cxcache.

This could be fixed by forcing the package folder in build.cmd:

nuget restore -PackagesDirectory packages

**Comment by jthelin** [comment]
BTW @rogerpengyu, the [GitHub OctoCat](https://github.com/octocat) seems to have eaten the XML code you posed in this thread!

Could you repost or edit to surrounded it by the 3-backticks "code fence" so we can read it?
https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks

\`\`\` xml
<?xml version="1.0" encoding="utf-8"?>
\<foo>
  \<bar/>
\</foo>
\`\`\`

Thanks,

**Comment by qintao1976** [comment]
I hit the same problem, and solved it by following:
http://stackoverflow.com/questions/4092759/is-it-possible-to-change-the-location-of-packages-for-nuget

Will send a PR to fix it.

Thanks

**Comment by qintao1976** [comment]
I think this problem is fixed by PR #208.

Thanks
