### ISSUE TITLE
review SparkCLR for deprecated API

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/SparkCLR#172]
As SparkCLR is upgraded to Spark 1.5.2, we need to review deprecation list for 1.4.1 (https://spark.apache.org/docs/1.4.1/api/java/deprecated-list.html#method) and cleanup SparkCLR to ensure it does not take any dependency on these methods and also does not provide the corresponding C# APIs in M1.

**Comment by skaarthik** [comment]
https://spark.apache.org/docs/1.5.2/api/java/deprecated-list.html#method is better. It covers deprecated methods in all versions from 1.3.0 to 1.5.2.

**Comment by ms-guizha** [comment]
I have done the review and found some issues 
<1>org.apache.spark.streaming.StreamingContext.awaitTermination(long) 
As of 1.3.0, replaced by awaitTerminationOrTimeout(Long), but it still exists in our code 
<2> org.apache.spark.sql.types.DataType.fromCaseClassString(String) 
As of 1.2.0, replaced by DataType.fromJson(), I can not find "fromJson" method in DataType.cs , only find "ParseDataTypeFromJson"
<3>org.apache.spark.sql.DataFrame.insertInto(String) 
As of 1.4.0, replaced by write().mode(SaveMode.Append).saveAsTable(tableName). insertInto still in DataFrame.cs
<4>org.apache.spark.sql.SQLContext.jsonFile(String) .As of 1.4.0, replaced by read().json().
org.apache.spark.sql.SQLContext.jsonFile(String, double) .As of 1.4.0, replaced by read().json().
JsonFile still exists in SqlContext.cs

**Comment by ms-guizha** [comment]
if you think the depredated API I have found  should be removed, let me know and I will try to remove.

**Comment by skaarthik** [comment]
Thanks @ms-guizha ! Please add [Obsolete] attribute to these deprecated methods with a brief comment on the replacing method similar to how spark has annotated the methods as deprecated with info on replacement methods. If the replacement method is missing in SparkCLR for any deprecated method, please add it or create a separate issue with the list of missing methods for others to grab.

**Comment by ms-guizha** [comment]
I will do that. Btw, I have no access to create a separate issue

**Comment by ms-guizha** [comment]
Another three APIs deprecated in DataFrame.cs
 
<5>org.apache.spark.sql.DataFrame.save(String, String, SaveMode) 
As of 1.4.0, replaced by write().format(source).mode(mode).save(path).
 
<6>org.apache.spark.sql.DataFrame.saveAsParquetFile(String) 
As of 1.4.0, replaced by write().parquet().
 
<7>org.apache.spark.sql.DataFrame.saveAsTable(String, String, SaveMode, Map) 
As of 1.4.0, replaced by write().format(source).mode(mode).options(options).saveAsTable(tableName).

**Comment by ms-guizha** [comment]
I have resolved <3>~<7>, as for <1> <2>, I am not sure whether I can just replace the API name , anyone who know can give me some advice

**Comment by skaarthik** [comment]
1 - rename the method to awaitTerminationOrTimeout
2 - looks like we do not use fromCaseClassString. You can skip this.

**Comment by ms-guizha** [comment]
ok , after finishing the rename for <1>, we can close this issue

**Comment by skaarthik** [comment]
Thanks @ms-guizha
