### ISSUE TITLE
add validation for samples

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/SparkCLR#174]
There are still lot of samples that do not have validation. Since we are using samples as our functional test suite, we need to add validation for all samples.

Samples are at https://github.com/Microsoft/SparkCLR/tree/master/csharp/Samples/Microsoft.Spark.CSharp

**Comment by ms-guizha** [comment]
anyone who has access to assign , please assign this to me

**Comment by tawan0109** [comment]
I think @jayjaywg  is working on this issue now.

**Comment by jayjaywg** [comment]
yes I am working this. @ms-guizha

**Comment by ms-guizha** [comment]
OK

**Comment by skaarthik** [comment]
@ms-guizha if you are interested you could take up one of the unit test improvements https://github.com/Microsoft/SparkCLR/issues/180 or https://github.com/Microsoft/SparkCLR/issues/179

**Comment by ms-guizha** [comment]
@skaarthik  you can assign me #179 first ~

**Comment by skaarthik** [comment]
@ms-guizha assigned #179 to you. Thanks.
