### ISSUE TITLE
improve unit test coverage in "Core" namespace

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/SparkCLR#178]
Following classes need improvements in unit test coverage. 
* Accumulator
* Broadcast
* SparkContext
* RDD
* StatusTracker

See code coverage numbers at https://codecov.io/github/Microsoft/SparkCLR/csharp/Adapter/Microsoft.Spark.CSharp/Core

**Comment by tawan0109** [comment]
Now the overall test coverage in `Core` namespace has approached `83.53%`, close this issue for now.

https://codecov.io/github/Microsoft/SparkCLR/csharp/Adapter/Microsoft.Spark.CSharp?ref=9be16a5869b9c9416732781045df8b08461a2dcc

**Comment by skaarthik** [comment]
Great job. Thanks @tawan0109
