### ISSUE TITLE
improve unit test coverage in "Sql" namespace

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/SparkCLR#179]
Following classes need improvements in unit test coverage.
* Functions.cs
* UserDefinedFunctions & corresponding methods in SqlContext
* Row
* Column

See code coverage numbers at https://codecov.io/github/Microsoft/SparkCLR/csharp/Adapter/Microsoft.Spark.CSharp/Sql

**Comment by ms-guizha** [comment]
this issue is done, we can close this issue

**Comment by skaarthik** [comment]
Thanks @ms-guizha
