### ISSUE TITLE
improve unit test coverage in utils

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/SparkCLR#180]
Following classes need improvements in unit test coverage.
* JsonSerDe
* PayloadHelper
* SerDe
* ConfigurationService

See code coverage numbers at https://codecov.io/github/Microsoft/SparkCLR/csharp/Adapter/Microsoft.Spark.CSharp

**Comment by tawan0109** [comment]
Current coverage: 
* JsonSerDe   97.37%
* PayloadHelper  98.26%
* SerDe   100%
* ConfigurationService  85%
