### ISSUE TITLE
improve unit test coverage in worker

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/SparkCLR#188]
Key code paths in worker like accumulators, broadcast variables etc. worker implementation not covered by unit tests.

See https://codecov.io/github/Microsoft/SparkCLR/csharp/Worker/Microsoft.Spark.CSharp/Worker.cs

**Comment by tawan0109** [comment]
All key code paths in worker are covered by UT now, the overall test coverage for Worker is almost 80%.
https://codecov.io/github/Microsoft/SparkCLR/csharp?ref=ef63d27014af3c48ee6d9b404804941fb4dcaaa8
