### ISSUE TITLE
DataFrame API review - new in 1.6.0

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/SparkCLR#279]
Add new DataFrame APIs to SparkCLR
* http://spark.apache.org/docs/1.6.0/api/scala/index.html#org.apache.spark.sql.DataFrame 
* http://spark.apache.org/docs/1.6.0/api/scala/org/apache/spark/sql/DataFrameNaFunctions.html
* http://spark.apache.org/docs/1.6.0/api/scala/org/apache/spark/sql/DataFrameReader.html
* http://spark.apache.org/docs/1.6.0/api/scala/org/apache/spark/sql/DataFrameStatFunctions.html
* http://spark.apache.org/docs/1.6.0/api/scala/org/apache/spark/sql/DataFrameWriter.html

**Comment by jayjaywg** [comment]
New Features of 1.6 which need actions:

- Session Management: https://issues.apache.org/jira/browse/SPARK-10810
Need to add new apis, newSession()

- Reading non-standard JSON files: https://issues.apache.org/jira/browse/SPARK-11745
Need to add comments of DataFrameReader.cs

New APIs:

 DataFrame:
- repartition(Column[] cols, int numPartitions = 0)
- sortWithinPartitions(string firstCol, params string[] otherCols)
- sortWithinPartitions(Column firstCol, params Column[] otherCols)

 SQLContext:
- getOrCreate()
- dropTempTable(string tableName)

**Comment by jayjaywg** [comment]
Done.
