### ISSUE TITLE
incorrect folder name "run" in instructions

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/SparkCLR#291]
https://github.com/Microsoft/SparkCLR/blob/master/notes/windows-instructions.md#instructions refer to a folder named "SparkCLR/run" incorrectly. It should be updated to "SparkCLR\build\runtime".

https://github.com/Microsoft/SparkCLR/blob/master/notes/linux-instructions.md also has this issue.

**Comment by cyruszhang** [comment]
pull request completed.
https://github.com/Microsoft/SparkCLR/pull/293
