### ISSUE TITLE
WorkerTest unit tests fail when using R# plugin with Visual Studio

### ISSUE THREAD

**Issue by cyruszhang** [Microsoft/SparkCLR#304]
If using NUnit3 Adapter, then the unit tests will succeed.

The problem is that location specified by WorkerTest->CreateServer->Assembly.GetExecutingAssembly() does not have CSharpWorker.exe. Resharper initiates NUnit tests in a different dir than the NUnit Adapter.

Test initialization code should be dev tool agnostic and succeed whether we are using R# or not.

**Comment by cyruszhang** [comment]
![image](https://cloud.githubusercontent.com/assets/2977989/13086468/36662c2e-d498-11e5-80f1-1ccbb7be6edd.png)

**Comment by cyruszhang** [comment]
Assembly.GetExecutingAssembly() when using R#:
![image](https://cloud.githubusercontent.com/assets/2977989/13086519/67606ee8-d498-11e5-8e10-fa3e09f63a05.png)

**Comment by jthelin** [comment]
Try turning off the "Shadow Copy" option in ReSharper unit test options.

ReSharper -> Options -> Tools -> Unit Testing

[ ] Shadow-copy assemblies being tested.

**Comment by cyruszhang** [comment]
Yes, that works. A simple code change would make this problem go away as
well.

On Tue, Feb 16, 2016 at 1:02 PM, Jorgen Thelin <notifications@github.com>
wrote:

> Try turning off the "Shadow Copy" option in ReSharper unit test options.
>
> ReSharper -> Options -> Tools -> Unit Testing
>
> [ ] Shadow-copy assemblies being tested.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/SparkCLR/issues/304#issuecomment-184873553>.
>



-- 
Cyrus, Yilei Zhang
+1 (312) 813 6818

**Comment by skaarthik** [comment]
Thanks for fixing this issue, @cyruszhang
