### ISSUE TITLE
Is it possible to use LINQ on Spark, especially on DataFrame by SparkCLR?

### ISSUE THREAD

**Issue by MRYingLEE** [Microsoft/SparkCLR#311]
I am new to SparkCLR. I found in the source code there are many references of "System.Linq" and a lot of IEnumerable<> methods. 

So I am wondering the possibility to use LINQ on Spark, especially on DataFrame.

Can someone clarify?

Thank you in advance,

Ying

**Comment by skaarthik** [comment]
Hi @MRYingLEE - LINQ is used in the SparkCLR implementation. However, the C# API available for DataFrame is consistent with the API in Scala/Java. You will not be able to do anything different in C# implementation of Spark driver. 

Hope this helps. If this response did not address your question, please reopen the issue.

**Comment by MRYingLEE** [comment]
Thank you to clarify.
Now I understand the current status. But I have further questions:

1. Is it possible to extend SparkCLR to support LINQ? And how much the workload?  At present I have a big concern that maybe LINQ cannot work on Spark due to "big" data. If it is not too difficult, I may try to do so.

2. Does Microsoft have a plan to do so in future?

Thank you in advance,

Ying
