### ISSUE TITLE
Build problem with VS2015 on VSO

### ISSUE THREAD

**Issue by jthelin** [Microsoft/SparkCLR#39]
The latest PR #38 seems to have broken my VSO build when using VSO's VS2015 (MsBuild 14) settings.

Build works ok when using VSO's VS2013 (MsBuild 12) settings, so i think it is similar problem to issue #8.

Paradoxically, my AppVeyor build also uses msbuild 14 and that works ok, so seems to be some specific problem with VSO environment :(
https://ci.appveyor.com/project/jthelin/sparkclr/build/1.4.1-SNAPSHOT.50

Sorry, i don't have VS2015 installed on any of my dev machines to suggest a PR fix for this issue.

```
csharp\Adapter\Microsoft.Spark.CSharp\Streaming\DStream.cs(427,38): Error CS0029: Cannot implicitly convert type 'T' to 'System.Collections.Generic.KeyValuePair<int, T>'

csharp\Adapter\Microsoft.Spark.CSharp\Streaming\DStream.cs(427,38): Error CS1662: Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type
```

**Comment by danielli90** [comment]
I have a VS 2015 installed locally - the build worked for me.

**Comment by jthelin** [comment]
> build worked for me.

Is that building in Visual Studio, or using MsBuild command line build?

**Comment by danielli90** [comment]
Sorry for not being clear. I used Developer Command Prompt for VS 2015

**Comment by jthelin** [comment]
OK, thanks for confirming @danielli90 

In the past some times VS and MsBuild give slightly different outcomes even for the same version, but not in this case.

Looks like this is most likely a bug in VSO then, so i'll close this issue and send bug report to VSO Team instead.
